version: 2.1
orbs:
    node: circleci/node@4.7.0
jobs:
    lint:
        executor: node/default
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
    test:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - run: npm install
            - run: docker run -d -p 20000:20000 -e block_time=2 tqtezos/flextesa:20210602 granabox start
            - run: npm run compile
            - run: sleep 30
            - run: npm run test
workflows:
    tests:
        jobs:
            - lint
            - test
